---
# tasks file for k8s_tools
- name: Get stable version of Kubectl
  become: true
  uri:
    url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"
    method: GET
    status_code: 200
    return_content: yes
  register: kubectl_release_version
  when: kubectl_version is not defined

- name: Set kubectl_version variable
  set_fact:
    kubectl_version: "{{ kubectl_release_version.content | replace('\n', '') }}"
  when: kubectl_version is not defined

- name: Install Kubectl
  become: true
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "{{ kubectl_bin_path }}"
    mode: "+rx"

- name: Check if Helm binary exists
  become: true
  stat:
    path: "{{ helm_bin_path }}"
  register: helm_check

- name: Check Helm version
  command: "{{ helm_bin_path }} version"
  failed_when: false
  changed_when: false
  register: helm_existing_version

- name: Download helm
  become: true
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
    mode: "0644"
  register: helm_download
  when: not helm_check.stat.exists or helm_version not in helm_existing_version.stdout

- name: Copy helm binary into place
  become: true
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "{{ helm_bin_path }}"
    mode: 0755
    remote_src: true
  when: helm_download is changed

- name: Cleanup /tmp
  become: true
  file:
    path: "/tmp/linux-amd64/"
    state: absent

- name: Install Helmfile
  become: true
  get_url:
    url: "https://github.com/roboll/helmfile/releases/download/{{ helmfile_version }}/helmfile_linux_amd64"
    dest: "{{ helmfile_bin_path }}"
    mode: "+rx"
